base_url = "https://mercury.flxzt.net/"
title = "Mercury Theme"
description = "Modern and minimalistic blog theme - Fork of the Apollo theme"
build_search_index = true
generate_feed = true
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
favicon = "/images/favicon.svg"
logo = "/images/logo.svg"
theme = "auto"      # either `auto`, `dark` or `light`

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/flxzt", icon = "twitter" },
    { name = "github", url = "https://github.com/flxzt/mercury", icon = "github" },
]

custom_css = []

[extra.analytics]
enabled = false
goatcounter_user = "your_user"
goatcounter_host = "example.com"    # default= goatcounter.com

[extra.footer]
enabled = true
# If footer is enabled, you can either set the text here or overwrite the `partials/footer.html` template for custom html
text = "John Doe - © 2022"